src/splitter_ims.py

When anyone try to connect a wrong source(address or port), system prints an error message and stops running.

exception handling : unable to connect to the source

---

src/lossy_peer.py
src/monitor_dbs.py
src/monitor_fns.py
src/monitor_lrs.py
src/peer_dbs.py
src/peer_fns.py
src/peer_ims.py

This commit overrides the `__new__` method in `Peer_IMS` to avoid creating several nested peer instances and copying their attributes and therefore simplifying the constructors.
The functionality of the instances is extended by setting `__class__` to the requested subclass and therefore keeping the attributes.
The constructors, i.e. the syntax of creating specialized peer instances, stays as before:
```
peer = Peer_IMS()
peer = Peer_DBS(peer)
```
The subclassing is happening implicitly in the `__new__` method.

Modified peer classes to avoid nesting and attribute copying.

---

src/peer_ims.py

Sometimes it might not be possible or desired for the peer to send packets to gmail.com (e.g. in a virtual machine setup where the peers don't have a direct connection to the internet).
This commit makes peers connect to the splitter IP address instead, as it has to be reachable from the peers anyway.

Make peers connect to splitter to get their public IP.

---

src/peer_dbs.py
src/peer_ims.py

Currently, to handle messages of custom format, peers inheriting from Peer_DBS have to copy the `process_next_message(self)` method and adapt it to new messages.
With this change, inheriting peers can override the `process_message(self, message, sender)` method and implement their case differentiation. In case the inheriting class does not handle the received message, the base class method can be called.

Split up process_next_message() to facilitate overriding.

---

src/malicious_peer.py
src/malicious_socket.py
src/peer.py
src/peer_strpeds.py
src/splitter.py
src/splitter_strpeds.py
tools/test_strpe.py

-It's now possible to test STrPe-DS with testing script:
```./test_strpe.py -n 10 -t 1 -m 2 -s```
`-s` option enables the STrPe-DS mode for peers.
-_malicious_ option for STrPe-DS peers: 
```./peer.py --use_localhost --player_port 10000 --strpeds --malicious```
Malicious STrPe-DS peer sends poisoned chunks.
-Improvement for STrPe-DS splitter: it gathers complains from trusted peers more often.
-Testing script for STrPe mechanism now stops when all malicious peer were excluded from the team (it checks splitter log file every 2 seconds)
-Some refactoring

STrPe-DS testing & some improvements

---

src/peer_dbs.py
src/splitter.py
src/splitter_dbs.py

This enables the user to set the number of monitors `n`, which are automatically the first `n` peers connecting to the splitter.

Added an option to splitter to set the number of monitors.

---

src/splitter.py
src/splitter_dbs.py

To determine if a given peer is a monitor peer, now you have to check not only the first peer `self.peer_list[0]` but the first number of peers `self.peer_list[0:self.MONITOR_NUMBER]`.
This is an addition to #64.

Adapted Splitter_DBS to fully use the number of monitors option.

---

src/splitter_nts.py

With these commits, messages from the splitter are not sent immediately, but to avoid network congestion they are stored in a queue and sent one after another, each after a new chunk from the source was received.

Implement simple congestion avoidance using message queue

---

doc/NTS/NAT_traversal.md
src/core/peer_ims.py
src/core/peer_nts.py
src/core/symsp_peer.py
src/peer.py
src/tools/cleanup_NAT_network.sh
src/tools/setup_NAT_network.sh
src/tools/test_NAT_traversal.sh
src/tools/testrun.sh
src/tools/testrun2.sh

This set of commits fixes Python3 support for NTS classes and the respective scripts.
It also improves the inheritance technique implemented in P2PSP: When a peer is instantiated, for each layer a temporary subclass with the required base class and methods is created, e.g. `Peer_IMS.Peer_DBS.Monitor_DBS.Peer_NTS.Monitor_NTS`.

Python3 fixes for NTS and test scripts; improved inheritance technique

---

src/splitter.cc

Use `std::unique_ptr` instead of raw instead. [`std::make_unique`](http://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique) can be used if using `C++14`.

Use std::unique_ptr instead of raw pointer

---

src/core/splitter_dbs.cc

The present condition always returns `false` and has several issues
-  `find` will return `peer_list_.begin() + monitor_number_` and not `peer_list_.end()` if the element is not found.`
- checks only for monitors?
The solution is to remove it since we anyways check inside `RemovePeer` or correct it to
`find(peer_list_.begin() + monitor_number_,peer_list_.end(), peer) == peer_list_.end()`
This is an attempt to fix #85

Remove peer properly when peer exceeds max chunk loss.

---

src/core/splitter_ims.cc

The exception from `boost::asio::ip` (`SIGABRT`) was not being caught by the catch block, hence core dumped was produced.
Attempts to fix #83.

Exit from splitter when address already in use while binding.

---

src/tools/test_UDP.py

Previous version was calculating average speed incorrect, because the first value was always zero and therefore average amount is always understated
> 0 Kbps ( average = 0 Kbps )
1446068 Kbps ( average = 723054 Kbps )
1440088 Kbps ( average = 962068 Kbps )
1445511 Kbps ( average = 1082931 Kbps )
1432338 Kbps ( average = 1152814 Kbps )
1441701 Kbps ( average = 1200963 Kbps )
I have just changed few lines and currently it is working correctly
> 1470857 Kbps ( average = 1470857 Kbps )
1438072 Kbps ( average = 1454473 Kbps )
1439735 Kbps ( average = 1449563 Kbps )
1461444 Kbps ( average = 1452535 Kbps )
1442185 Kbps ( average = 1450467 Kbps )
1455923 Kbps ( average = 1451378 Kbps )
I am trying to get used to the code base for GSoC, so I thought that fixing some minor bugs would be useful.

test_UDP.py output slightly changed to be more accurate

---

src/core/common.h
src/core/splitter_dbs.cc
src/core/splitter_dbs.h
src/core/splitter_strpe.cc
src/splitter.cc

This commit enables the splitter to create the splitter instance depending on the runtime flags.
For Set-of-Rule-dependent parameters, checking and casting to the needed subclass is done.
EDIT: If you planned or already started a different implementation, just drop a comment.

Dynamically select Sets of Rules at splitter

---

src/core/peer_ims.py

We receive a negative chunk number whenever there is a socket timeout (process_next_message() function). However in line 479, we keep on waiting for the chunks whenever there is a negative chunk number.
If the splitter removes a particular peer from the peer_list, the splitter no longer sends the chunks to the peer , so do the other peers.
Also, since this is a UDP socket, there might be packet losses.
Hence, technically the peer will never get to know if the socket timeout is because of UDP or because it was removed from the peer_list.
One way to resolve this issue is to wait for a certain amount of time before stopping the peer thread.
I have chosen this time interval as 15 seconds. This can be modified as required.

Fixed proper exit of a peer after removal from peer_list

---

src/core/splitter_dbs.cc

When a new connection arrives, if the connection is from an existing peer in the `peer_list_` comes then only it's 'losses_' is being set to zero. But, its position on the 'peer_list_' remains same. This causes an indifference between pre-existing and new-coming peers while calculating `ComputeNextPeerNumber`. They should actually be treated like a new-coming peer always even if it does exist on the `peer_list_` before.

Insert pre-existing peers at the end of peer list

---

make.py
src/util/trace.h

made some changes to the tracing module so that in non-debug builds only
error messages will be logged.
modified `make.py` to show which mode (build or release) is being build
for.
while building in debug mode make commands verbosity option is set. so,
that it is easier to figure out which compiler flags are being passed.

only error message logging for non-debug builds

---

src/core/common.h
src/core/peer_dbs.cc
src/core/peer_dbs.h
src/core/peer_ims.cc
src/core/peer_ims.h
src/core/python.cc
src/core/splitter_dbs.cc
src/core/splitter_ims.cc
src/core/splitter_ims.h
src/core/trusted_peer.h

This doesn't change anything substantial, just cleans up the code a bit.
Used scripts snippets:
`sed -i 's/\t/        /g' src/core/*{cc,h}` and `sed -i 's/  *$//g' src/core/*{cc,h}`.

Indentation by spaces, no trailing whitespace

---

CMakeLists.txt

This will fix compilation on Travis CI build servers, and allows automatic compilation checks again.

Fix Boost::Python in CMakeLists for Travis CI builds

---

CMakeLists.txt
make.py

- use multiprocessing module instead of system call in make.py
- add .so suffix when building on OSX in CMakeLists.txt

fix OSX issues with building P2PSP

---

src/core/monitor_nts.h
src/core/peer_nts.h
src/core/splitter_core.cc
src/core/splitter_nts.cc
src/core/splitter_nts.h

This fixes NTS functionality (`SendTheListOfPeers()` was called twice due to recent changes). Also, the header size was increased to 8192, to make an Ogg video playable again.
The `protected` attributes of NTS methods were fixed, to make methods protected and callable, respectively.

Fix NTS, increase header size, fix 'protected' attributes for NTS methods.

---

src/core/monitor_dbs.cc
src/core/monitor_dbs.h
src/core/monitor_ems.cc
src/core/monitor_ems.h
src/core/monitor_nts.cc
src/core/monitor_nts.h
src/core/peer_dbs.cc
src/core/peer_dbs.h
src/core/peer_ems.cc
src/core/peer_nts.cc
src/core/peer_nts.h
src/core/splitter_dbs.cc
src/core/splitter_ems.cc
src/core/splitter_nts.cc
src/core/splitter_nts.h

This small change in the code lets the P2PSP team handle the arrival of monitors dynamically. The number of monitors need not be set while creating the team. 
This allows monitor peers to connect to the splitter on the go.
Modified layers
- DBS
- NTS
- EMS

Dynamic creation of monitors in a P2PSP team

---

make.py

@vicente-gonzalez-ruiz I automated the download and compilation process as you suggested and user can use the new downloaded Boost libraries rather than system libraries. The compilation runs fine, but I get some `CMake` warnings([link](http://pastebin.com/iGkbKZJU)). I think the reason why we get these warnings is because system has old libraries.Apart from that all the automation works fine.

added Boost download, compilation before using it

---

src/core/splitter_core.cc

Please ignore whitespace changes, somehow my editor is being much more sensitive to trailing spaces.
The only changes are at line [255](https://github.com/P2PSP/core/pull/130/files#diff-7a17709b3f56f910fc0217a212a06fe1L255) and [285](https://github.com/P2PSP/core/pull/130/files#diff-7a17709b3f56f910fc0217a212a06fe1L285).

Fix conditional increment of send and receive counters
